version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: hub-api/Dockerfile
    volumes:
      - ./hub-api:/var/www/html
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - '8080:80'
    networks:
      - internal
    
  php: 
    image: php:8.3-fpm-alpine
    volumes:
      - ./hub-api:/var/www/html 
    networks:
      - internal

  node:
    build:
      context: ./hub-fe 
    volumes:
      - ./hub-fe/src:/app/src
    ports: 
      - '8000:3001'
    networks:
      - internal

networks:
  internal:
    driver: bridge
