version: '3'

services:
  hub-api:
    build:
      context: .
      dockerfile: hub-api/Dockerfile
    container_name: hub-api
    # volumes:  
    #   - ./hub-api:/var/www/html 
    ports:
      - '8080:80'
    networks:
      - internal
    
  mysql:
    image: mysql:8.0.1
    container_name: hub-db
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret  
    ports:
      - 3306:3306
    networks:
      - internal
 
  node:
    build:
      context: ./hub-fe 
    container_name: hub-fe
    # volumes:
    #   - ./hub-fe/src:/app/src
    ports: 
      - '8000:3001'
    networks:
      - internal

networks:
  internal:
    driver: bridge
